<a href="https://colab.research.google.com/github/geeta7777chavan-boop/python-practicals/blob/main/practical_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name : Geeta Santosh Chavan**

**Roll No. : AIDS-SY-A-66**

# **Practical No. 3: Data Wrangling with Pandas**

**Aim :**

To perform data wrangling using the pandas library in Python to manipulate and transform data for analysis.

# **Theory :**

**1. What is data wrangling? Explain the difference between data wrangling and data preprocessing.**

Data Wrangling (also known as Data Munging) is the process of cleaning, transforming, structuring, and enriching raw data into a more suitable and usable format for analysis, visualization, and machine learning.

It includes tasks such as:


*   Handling missing values
*   Removing duplicates


*   Renaming columns
*   Changing data types


*   Merging multiple datasets
*   Creating new derived columns


*   Filtering and reshaping data

**Difference between Data Wrangling and Data Preprocessing:**

| Aspect        | Data Wrangling                                      | Data Preprocessing                                      |
|--------------|-----------------------------------------------------|---------------------------------------------------------|
| Definition    | Transforming raw data into a usable format          | Preparing data specifically for modeling                |
| Scope         | Broader (includes ingestion & transformation)       | Narrower (focuses on final model-ready data)            |
| Stage         | Early to middle stage                               | Later stage (after wrangling)                           |
| Main Goal     | Make data clean and structured                      | Optimize data for algorithms                            |
| Examples      | Merging files, pivoting, reshaping                  | Scaling, encoding categorical variables, train-test split |

In simple terms:

Data Wrangling → Makes messy data usable.

Data Preprocessing → Makes usable data suitable for machine learning algorithms.

**2. What is the importance of Exploratory Data Analysis (EDA) in Pandas?**

Exploratory Data Analysis (EDA) is the process of analyzing and summarizing the main characteristics of a dataset, often using visual and statistical methods, before applying formal modeling or machine learning techniques.

**Importance of EDA in Pandas:**


*   Helps understand the structure, distribution, and patterns in the data.

*   Identifies missing values, outliers, and anomalies.

*   Reveals relationships and correlations between variables.
*   Detects data quality issues early.


*   Guides feature selection and engineering decisions.


*  Prevents wrong assumptions during modeling.


*   Provides insights that drive business or research decisions.

Pandas plays a central role in EDA through functions like describe(), info(), value_counts(), groupby(), correlation matrices, and integration with visualization libraries like Matplotlib and Seaborn.

**3. What are the main differences between Series, DataFrame, and Panel?**

| Feature        | Series                                  | DataFrame                                      | Panel (Deprecated)                          |
|---------------|------------------------------------------|------------------------------------------------|---------------------------------------------|
| Definition     | 1D labeled array                        | 2D labeled data structure                      | 3D data structure                           |
| Dimensions     | One-dimensional                         | Two-dimensional                                | Three-dimensional                           |
| Structure      | Single column of data                   | Multiple columns (table format)                | Collection of DataFrames                    |
| Data Types     | Homogeneous (same type usually)         | Heterogeneous (different types allowed)        | Heterogeneous                               |
| Indexing       | Uses single index                       | Uses row and column index                      | Uses major, minor, and item axes            |
| Example        | [1, 2, 3]                               | Table with rows & columns                      | Stack of multiple tables                    |
| Usage          | Simple data handling                    | Data analysis and manipulation                 | Multi-dimensional data (rarely used now)    |
| Status         | Actively used                           | Actively used                                  | Deprecated (removed from modern Pandas)     |

**4. Explain the use of the following functions:**

`a. isnull()`

Returns a boolean DataFrame/Series indicating where values are missing (NaN or None).
Used to detect missing data.

`b. notnull()`

Opposite of isnull(). Returns True for non-missing values.
Helpful to filter out rows/columns that have valid data.

`c. dropna()`

Removes rows or columns containing missing values.
Parameters: axis=0 (rows), axis=1 (columns), how='any' or 'all', thresh, inplace.

`d. fillna()`

Fills missing values with a specified value, method, or statistical measure (mean, median, mode).
Common strategies: forward fill (ffill), backward fill (bfill), or constant value.

These four functions are fundamental for missing value treatment during data wrangling.

**5. What is column transformation and why is it important in data analysis?**

Column Transformation refers to the process of creating new columns or modifying existing columns based on certain logic, calculations, or functions.

**Common ways to transform columns in Pandas:**


*   Using arithmetic operations `(df['new_col'] = df['col1'] + df['col2'])`
*   Applying functions `(df['new_col'] = df['col'].apply(lambda x: ...))`


*   Using `map()`, `replace()`, or `astype()`
*   Feature engineering (e.g., extracting day/month from date)

**Why it is important:**

Helps create more meaningful and informative features.
Improves model performance through better feature engineering.
Converts raw data into domain-specific insights.
Enables data normalization and standardization.
Supports creation of derived metrics (e.g., Total Price = Quantity × Unit Price).

Column transformation turns raw data into actionable intelligence.

# **Program :**

In [ ]:
# Upload file manually
from google.colab import files
uploaded = files.upload()

Saving Nutrition_Value_Dataset.csv to Nutrition_Value_Dataset.csv

In [ ]:
import pandas as pd
# Load dataset (replace file name if needed)
df = pd.read_csv('Nutrition_Value_Dataset.csv')

df.head()

,Company,Category,Product,Per Serve Size,Energy (kCal),Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg)
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            530 non-null    object
 1   Category           530 non-null    object
 2   Product            530 non-null    object
 3   Per Serve Size     530 non-null    object
 4   Energy (kCal)      530 non-null    float64
 5   Carbohydrates (g)  530 non-null    float64
 6   Protein (g)        530 non-null    float64
 7   Fiber (g)          530 non-null    float64
 8   Sugar (g)          530 non-null    float64
 9   Total Fat (g)      530 non-null    float64
 10  Saturated Fat (g)  530 non-null    float64
 11  Trans Fat (g)      530 non-null    float64
 12  Cholesterol (mg)   530 non-null    float64
 13  Sodium (mg)        443 non-null    float64
dtypes: float64(10), object(4)
memory usage: 58.1+ KB

In [ ]:
df.columns

Index(['Company', 'Category', 'Product', 'Per Serve Size', 'Energy (kCal)',
       'Carbohydrates (g)', 'Protein (g)', 'Fiber (g)', 'Sugar (g)',
       'Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)',
       'Cholesterol (mg)', 'Sodium (mg)'],
      dtype='object')

**1. Select a single column**

In [ ]:
df['Energy (kCal)']

0      432.60
1      407.60
2      423.33
3      474.03
4      408.16
        ...
525    352.90
526    461.20
527    667.50
528    322.60
529    582.90
Name: Energy (kCal), Length: 530, dtype: float64

**2. Add a new column**

In [ ]:
df['Country'] = 'India'
df.head()

,Company,Category,Product,Per Serve Size,Energy (kCal),Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72,India
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00,India
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22,India
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11,India
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67,India

**3. Sort by Energy**

In [ ]:
df.sort_values(by='Energy (kCal)', ascending=False).head()

,Company,Category,Product,Per Serve Size,Energy (kCal),Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country
401,KFC,All Meals,10 Pc Fried Leg,1000.0,2880.0,85.1,178.6,45.0,0.0,82.6,33.0,0.20,112.0,1.1,India
419,KFC,All Meals,"Super Sixes (4 HC, 6 HW,\n8 Strips)",962.0,2816.5,39.5,172.1,23.0,0.0,41.5,17.0,0.08,57.0,0.8,India
418,KFC,All Meals,Triple Treat (4 HC + 4\nSmoky + 6 Boneless\nSt...,1008.0,2475.4,41.7,203.0,24.0,0.0,43.1,16.6,0.07,59.0,0.9,India
417,KFC,All Meals,10 for 550\n(10 pc HC)\non Wednesdays,910.0,2382.2,38.8,143.3,28.0,0.0,49.8,19.7,0.11,70.0,0.7,India
415,KFC,All Meals,Friendship Bucket DL(3pc HC+3pc HW+3pc Strips ...,693.5,2131.4,41.1,124.8,23.0,0.0,42.2,17.5,0.07,58.0,0.9,India

**4. Rename column**

In [ ]:
df.rename(columns={'Energy (kCal)': 'Energy'}, inplace=True)
df.head()

,Company,Category,Product,Per Serve Size,Energy,Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72,India
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00,India
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22,India
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11,India
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67,India

**5. Summary statistics**

In [ ]:
df.describe()

,Energy,Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg)
count,530.000000,530.000000,530.000000,530.0000,530.000000,530.000000,530.000000,530.000000,530.000000,443.000000
mean,377.304470,39.442302,16.710340,inf,8.276226,13.228528,5.946302,0.279443,118.620434,422.431578
std,338.315722,21.196943,24.425784,NaN,12.186627,10.740934,4.844024,3.265604,502.865434,471.300077
min,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,180.750000,24.227500,5.000000,1.6900,0.000000,5.000000,2.500000,0.030000,9.462500,1.450000
50%,329.645000,38.570000,11.445000,3.0000,3.200000,12.600000,5.240000,0.110000,30.085000,220.000000
75%,451.812500,54.120000,20.005000,5.9975,9.850000,18.360000,8.095000,0.207500,77.535000,754.975000
max,2880.000000,137.800000,203.000000,inf,64.220000,82.600000,33.000000,75.260000,9769.700000,2399.490000

**6. Filter rows (High Energy + High Protein)**

In [ ]:
df[(df['Energy'] > 300) & (df['Protein (g)'] > 10)]

,Company,Category,Product,Per Serve Size,Energy,Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72,India
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00,India
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22,India
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,3.79,0.0,20.26,9.25,0.33,71.72,1128.11,India
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,2.46,0.0,12.53,4.90,0.14,48.09,942.67,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,Dominos,All Meals,ZINGY PARCEL VEG,180.0,620.40,69.50,16.90,18.12,8.8,30.50,15.10,0.60,2119.75,NaN,India
525,Dominos,All Meals,CHICKEN WINGS,174.0,352.90,24.50,35.30,5.76,10.4,12.60,4.80,0.19,308.70,NaN,India
526,Dominos,All Meals,CRISPY CHICKEN STRIPS,156.0,461.20,51.30,26.70,5.16,3.6,13.90,4.30,0.17,713.07,NaN,India
527,Dominos,All Meals,ZINGY PARCEL CHICKEN,210.0,667.50,17.30,19.20,16.92,10.6,31.30,14.10,0.56,541.49,NaN,India
529,Dominos,All Meals,CALZONE POCKETS - CHICKEN,248.0,582.90,101.00,18.60,5.04,12.2,11.60,4.20,0.17,1171.60,NaN,India

**7. Group by Category (mean Energy)**

In [ ]:
df.groupby('Category')['Energy'].mean()

Category
All Meals                           441.224328
BREAKFAST MENU                      286.248750
CONDIMENTS MENU                      47.473333
Cookies, Brownies & Bars            305.555556
Croissants, Danishes & Bagels       294.444444
DESSERTS MENU                       553.507000
Fruit & Yogurt                      233.333333
GOURMET MENU                        143.326471
Hot Breakfast                       274.166667
Loaves, Coffee Cakes & Cake Pops    360.000000
McCAFE MENU                         168.712833
REGULAR MENU                        367.737778
Seasonal Bakery Offerings           371.666667
Name: Energy, dtype: float64

**8. Merge two DataFrames**

In [ ]:
df2 = df[['Product', 'Energy']]

merged_df = pd.merge(df, df2, on='Product')
merged_df.head()

,Company,Category,Product,Per Serve Size,Energy_x,Carbohydrates (g),Protein (g),Fiber (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country,Energy_y
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72,India,432.60
1,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,3.85,0.0,10.93,5.14,0.16,16.19,499.72,India,332.61
2,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00,India,407.60
3,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,7.19,0.0,8.03,3.24,0.11,66.80,818.00,India,376.45
4,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,3.49,0.0,12.27,5.23,0.18,19.75,638.22,India,423.33

**9. Handle missing values (IMPORTANT FIX)**

In [ ]:
# Since Sodium has missing values, handle it properly:
df['Sodium (mg)'] = df['Sodium (mg)'].fillna(df['Sodium (mg)'].mean())

In [ ]:
df.isnull().sum()

Company              0
Category             0
Product              0
Per Serve Size       0
Energy               0
Carbohydrates (g)    0
Protein (g)          0
Fiber (g)            0
Sugar (g)            0
Total Fat (g)        0
Saturated Fat (g)    0
Trans Fat (g)        0
Cholesterol (mg)     0
Sodium (mg)          0
Country              0
dtype: int64

In [ ]:
# Drop a column (example: Fiber)
df.drop(columns=['Fiber (g)'], inplace=True)

**10. Apply function**

In [ ]:
df['High_Calorie'] = df['Energy'].apply(lambda x: 'Yes' if x > 300 else 'No')
df.head()

,Company,Category,Product,Per Serve Size,Energy,Carbohydrates (g),Protein (g),Sugar (g),Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Country,High_Calorie
0,Pizza Hut,All Meals,Corn n Cheese (Personal),143.5 g,432.60,65.64,17.91,0.0,10.93,5.14,0.16,16.19,499.72,India,Yes
1,Pizza Hut,All Meals,Country Feast (Personal),178 g,407.60,67.11,16.73,0.0,8.03,3.24,0.11,66.80,818.00,India,Yes
2,Pizza Hut,All Meals,Double Cheese (Personal),143 g,423.33,59.97,18.26,0.0,12.27,5.23,0.18,19.75,638.22,India,Yes
3,Pizza Hut,All Meals,Double Paneer Supreme (Personal),174.5 g,474.03,52.86,20.07,0.0,20.26,9.25,0.33,71.72,1128.11,India,Yes
4,Pizza Hut,All Meals,Farmer`s Pick (Personal),177 g,408.16,53.93,19.91,0.0,12.53,4.90,0.14,48.09,942.67,India,Yes

# **Conclusion**

In this practical, we learned that data wrangling is a crucial step that transforms raw data into a clean and structured format suitable for analysis. Through various Pandas techniques like handling missing values and column transformations, we can prepare high-quality data. Effective data wrangling significantly improves the accuracy and reliability of data analysis and machine learning models.